### ISSUE TITLE
Rename  example files

### ISSUE THREAD

**Issue by Adminius** [KONNEKTING/KonnektingDeviceLibrary#1]
because of Arduino IDE restrictions (foldername=filename), pls. rename example files to 
**DemoSensor_Temp_RH.ino** and **DemoSensor_Temp_RH.xml**.
thx

**Comment by tuxedo0801** [comment]
Solved:

https://github.com/KONNEKTING/KonnektingDeviceLibrary/commit/d2aff6e5a3db3d4137621ce2376d75bb444c8934
https://github.com/KONNEKTING/KonnektingDeviceLibrary/commit/01abb3efb6c3df230676bd77e3dc293b9ca88ae9
