### ISSUE TITLE
Test sketch to verify Arduino<=>BCU communication

### ISSUE THREAD

**Issue by fluppie** [KONNEKTING/KonnektingDeviceLibrary#10]
It would be very handy to have a sketch to test the communication between an Arduino and the BCU.

A very basic write sketch. E.g. writing a 1 to 0/0/1 every 10 seconds. So with the group address monitor we can easily check the KNX telegrams.

Also maybe a simple read sketch to read a group address 0/0/1 it's value and print the result to SoftSerial.

Everything hardcoded so it's easy to get it running.

**Comment by tuxedo0801** [comment]
Solved with PR #11
