### ISSUE TITLE
isIdle() check

### ISSUE THREAD

**Issue by Adminius** [KONNEKTING/KonnektingDeviceLibrary#14]
Please create a function (e.g. isIdle()) that replaces this statement: "!Tools.getProgState() && !Tools.isFactorySetting()"

**Comment by tuxedo0801** [comment]
already implemented. See: 

https://github.com/KONNEKTING/KonnektingDeviceLibrary/blob/develop_beta4/KonnektingDevice.cpp#L271

bool KonnektingDevice::isReadyForApplication()
