### ISSUE TITLE
Debug.print for float values.

### ISSUE THREAD

**Issue by Adminius** [KONNEKTING/KonnektingDeviceLibrary#30]
It is not possible to print float values:
```
Debug.print(F("Temperature: f%"),currentTemp);
```

**Comment by tuxedo0801** [comment]
This is not related to KONNEKTING code. It's related to the AVR Microcontroller and the arduino core code that cannot handle float values in printf() functions. One has to convert the float to a string (and decide how many decimals should be used etc..):

Use this code-snippet as a guide to solve the issue:

```c++
 // convert float to string with 3 decimals 
float f = 123.456789f;

char str1[20];
dtostrf(f,1,3,str1);

Debug.println(F("myFloat=%s"), str1); // --> "123.46"
```
