### ISSUE TITLE
Add support for DPT 19.001 DateTime

### ISSUE THREAD

**Issue by hasselk** [KONNEKTING/KonnektingDeviceLibrary#32]
Ive made the modifications to KnxDPT.h to add DPT 19.001
Helper Funktions to get/set Data are missing at the moment, ill add them later on.

will add a pull request too
https://github.com/KONNEKTING/KonnektingDeviceLibrary/pull/33

thanks

**Comment by tuxedo0801** [comment]
Merged PR #33
