### ISSUE TITLE
KnxTools::reboot() on Mega644pa

### ISSUE THREAD

**Issue by mrniemand** [KONNEKTING/KonnektingDeviceLibrary#40]
The mega644pa seems to have the same issue like the 328p.
So this type also needs the asm volatile ("  jmp 0"); for rebooting.

Is there any adavantage for the watchdog version instead of the jmp 0?

**Comment by tuxedo0801** [comment]
mega644 ist not supported :-(

Supported µC:

* 328p
* 32u4
* esp8266
* samd21

**Comment by tuxedo0801** [comment]
See also:

**Comment by tuxedo0801** [comment]
We will add a flag that you have to set via `#define ...` to force the asm-jmp-reboot.

**Comment by tuxedo0801** [comment]
#ifdef starts with all supported µC, and last #else will use soft reset. ---> All unsupoprted µC will then use soft reset.
See: https://github.com/KONNEKTING/KonnektingDeviceLibrary/pull/44/commits/f32d9c3b693c6a02698aa89f191db72e49c81e59 + swap last wdt with soft reset

**Comment by Adminius** [comment]
beta4a was released. we are now using asm-reset for all AVR´s.
@mrniemand pls check if it solves your issue

**Comment by Adminius** [comment]
feature seems to work. i will close this issue. 
in case of problems, pls reopen it.
