### ISSUE TITLE
INIT-read request should be done only one time

### ISSUE THREAD

**Issue by Adminius** [KONNEKTING/KonnektingDeviceLibrary#47]
AS IS: infinity loop with init-requests
TO BE: only one init read request. if no answer -> undefined value

**Comment by tuxedo0801** [comment]
How do you define "undefined value"? 0x00? 0xFF? Both can have different meanings.

**Comment by Adminius** [comment]
int tmp = 0; is defined value
int tem; is undefined value

**Comment by tuxedo0801** [comment]
But 0 could also be a valid value... You would need an extra flag to "flag" this value as "undefined". But what does you KO answer if one reads it's value? You "have to" reply an value. There's no option to tell in the answer that the value is undefined.

**Comment by tuxedo0801** [comment]
```
int tmp = 0; is defined value
int tem; is undefined value <---- How do you "detect" that a variable is "not initialized"?
```

**Comment by tuxedo0801** [comment]
Just tested:

If you define a global variable like this:

```
int foo; 
```

and do a console print with the value if this variable, you get 0. 

So there is no way to detect uninitialized values. 

The only thing we could do:

create a delay in the "read" loop for init-comobjs to reduce the speed a bit and maybe do it only for a specific amount of time, let's say 20sec or 1min to give the device a chance to startup if the queried device is not reachable at all.

**Comment by Adminius** [comment]
another way:
INIT function should be called only on device start.
after one init-read-execution we set a global comObjInit = true flag.
That means, that init-read will never be called anymore (until device reset)
if no one "answers" knxEvents will not be called -> FW developer should take care of default values

**Comment by tuxedo0801** [comment]
So you suggest to just read once? Why not read f.i. at most 10 times with 1sec delay? That would enable the device to get an init value, even if the bus is temporarily overloaded?

Maybe we should also read the knx spec. Or we try an existing device, configure an comobj for init-read and apply an adress that is not available and see what happens.

**Comment by Adminius** [comment]
Yes, just once... 
My "not konnekting" device do it just once too...

**Comment by tuxedo0801** [comment]
ok, then we do the same.

**Comment by tuxedo0801** [comment]
merged, close for now.
