### ISSUE TITLE
Busware USB/KNX interface can not work?

### ISSUE THREAD

**Issue by Jason0416** [KONNEKTING/KonnektingDeviceLibrary#65]

**Comment by tuxedo0801** [comment]
1st of all: please provide more information.

2nd:

We did not test for busware interface, but in principle, it's just a usb-rs232 to KNX Transceiver interface, so it should work. But question is: why do you want to put a USB-KNX Interface to an arduino? Remember: You posted your question on the KonnektingDeviceLibrary repository. 

If you want to use the interface in combination with the KONNEKTING Suite, then it should work, if the appropriate firmware is on the interfacce. But as I said: We did not test this and without any further information, we cannot give any advise to to get it to work.

br,
Alex

**Comment by Jason0416** [comment]
OK，Move to KONNEKTING suite.
